name: Build Kivy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential zip unzip openjdk-11-jdk
        pip3 install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init || true
        sed -i 's/^requirements.*/requirements = python3,kivy/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk